# Generated by Django 5.0.1 on 2024-02-02 05:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyApp', '0002_user_phonenumber_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True, verbose_name='news'),
        ),
    ]
