# Generated by Django 5.0.1 on 2024-02-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyApp', '0003_alter_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='news'),
        ),
    ]
