# Generated by Django 5.0.1 on 2024-02-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyApp', '0005_alter_user_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='present_CTC',
        ),
        migrations.AddField(
            model_name='user',
            name='expected_CTC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_CTC',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='news'),
        ),
    ]
